#!/bin/bash

echo "/* autogenerated file */" > data.h
for x in img/*.png ; do build/png2bmp $x ; done
for x in img/*.bmp ; do build/zopfli -v $x ; done
rm img/*.bmp
for x in img/*.bmp.gz ; do build/file2c $x >> data.h ; done
rm img/*.bmp.gz
for x in snd/*.mod ; do build/file2c $x >> data.h ; done
for x in snd/*.wav ; do build/file2c $x >> data.h ; done

echo "/* autogenerated file */" > levels.h
for x in lev/*.dat ; do build/file2c $x >> levels.h ; done
